<a href="https://colab.research.google.com/github/Nandini13-rgb/Hello-world/blob/master/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
print(type(x))

y = np.array([[1,2,3,4],[12,3,5,6]])
print('\n', y)
print(y.shape)
print(y.size)
print(y.dtype)

z = np.array([[1.2,1.2,1.3], [5.4,3.4,2.6]], dtype = np.int64)
print(z)

t = np.zeros((3,4))
print()
print(t)
print()

T = np.zeros((3,4), dtype = np.int64)
print(T)

P = np.ones((3,4))
print()
print(P)

R = np.full((3,4), 5)
print()
print(R)

I = np.eye(3)
print()
print(I)

E = np.diag([1,2,3,4,5])
print()
print(D)

A = np.arange(10)
print()
print(A)

B = np.arange(2,12)
print()
print(B)

C = np.arange(1,14,2)
print()
print(C)

D = np.linspace(0,25,10)
print()
print(D)

F = np.linspace(0,25,10, endpoint = False)
print()
print(F)



[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>

 [[ 1  2  3  4]
 [12  3  5  6]]
(2, 4)
8
int64
[[1 1 1]
 [5 3 2]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

[0 1 2 3 4 5 6 7 8 9]

[ 2  3  4  5  6  7  8  9 10 11]

[ 1  3  5  7  9 11 13]

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


Reshape

In [ ]:
import numpy as np
x = np.arange(20)

print(x)

x = np.reshape(x,(4,5))
print()
print(x)

x = np.arange(20).reshape(4,5)
print()
print(x)

x = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print()
print(x)

x = np.random.random((3,3))
print()
print(x)

x = np.random.randint(4,16 , size = (3,3))
print()
print(x)

x = np.array([1,2,3,4])
print()
print(x[1])

x = np.random.randint(4,16 , size = (3,3))
print()
print(x)
print()
print(x[0,0])
print(x[2][2])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

[[0.07747232 0.72946621 0.656619  ]
 [0.93185414 0.77196383 0.41125541]
 [0.92011024 0.73297427 0.79338598]]

[[14  4  6]
 [11 10  4]
 [ 4 11  7]]

2

[[15 13  4]
 [15  5 11]
 [ 5  8 15]]

15
15


Deletion

In [ ]:
import numpy as np 
x = np.array([1,2,3,4])
print(x)
print()
x = np.delete(x, [0,3])
print(x)
print()

y = np.array([[1,2],[4,5]])
print(y)
print()

v = np.delete(y,0,axis = 0) # row 
print(v)
print()

u = np.delete(y,1,axis = 0)
print(u)
print()

w = np.delete(y,0,axis=1) #column
print(w)
print()

m = np.delete(y,1,axis=1)
print(m)
print()

[1 2 3 4]

[2 3]

[[1 2]
 [4 5]]

[[4 5]]

[[1 2]]

[[2]
 [5]]

[[1]
 [4]]



Append

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([[1,2,3],[4,5,6]])
print(x)
print()
x = np.append(x,6)
print(x)
print()

x = np.append(x,[7,8])
print(x)
print()

print(y)
print()

v = np.append(y,[[7,8,9],[10,11,12]],axis = 0)
print(v)
print()

u = np.append(y,[[4],[7]],axis =1)
print(u)
print()


[1 2 3 4 5]

[1 2 3 4 5 6]

[1 2 3 4 5 6 7 8]

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2 3 4]
 [4 5 6 7]]



Slicing

In [ ]:
import numpy as np
x = np.arange(20).reshape(4,5)
print(x)
print()

#second to fourth row and second to fourth column
z = x[1:4,2:5]
print(z)
print()

z = x[0:,2:5]
print(z)
print()

z = x[0:,0:]
print(z)
print()

z = x[:,2]
print(z)
print()

z = x[:,2:3]
print(z)
print()

z = x[2,:]
print(z)
print()


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 2  7 12 17]

[[ 2]
 [ 7]
 [12]
 [17]]

[10 11 12 13 14]



Arithmetic Operation

In [ ]:
import numpy as np
x = [1,2,3,4,5]
print(x)
print()
y = np.arange(5)
print(y)
print()

z = np.add(x,y)
print(z)
print()

print(x+y)
print()

X = np.arange(4).reshape(2,2)
Y = np.arange(4).reshape(2,2)
print(X)
print()
print(Y)
print()

Z = np.add(X,Y)
print(Z)
print()

print(X+Y)
print()

print(np.multiply(X,Y))
print()

print(np.divide(X,Y))
print()

print(X+3)
print()

print(x)
print()

print(np.exp(x))
print()

print(np.sqrt(x))
print()

print(np.power(x,3))
print()

[1, 2, 3, 4, 5]

[0 1 2 3 4]

[1 3 5 7 9]

[1 3 5 7 9]

[[0 1]
 [2 3]]

[[0 1]
 [2 3]]

[[0 2]
 [4 6]]

[[0 2]
 [4 6]]

[[0 1]
 [4 9]]

[[nan  1.]
 [ 1.  1.]]

[[3 4]
 [5 6]]

[1, 2, 3, 4, 5]

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[1.         1.41421356 1.73205081 2.         2.23606798]

[  1   8  27  64 125]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in true_divide


Boolean Indexing

In [ ]:
import numpy as np
x = np.arange(25).reshape(5,5)
print(x)
print()
#larger than 10
y = x[x>10]
print(y)

#smaller than 10
y = x[x<10]
print(y)

#inequality
y = x[x<=10]
print(y)

#between 10 & 17
y = x[(x<17) & (x>10)]
print(y)

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
x[(x > 10) & (x < 17)] = -1
print(x)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


Sorting

In [5]:
import numpy as np
x = np.random.randint(1,11, size = 10)
print(x)

print(np.unique(x))

print(np.sort(x))

x.sort()
print(x)

# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))

[ 7  3  6  9  6  4  2 10  7  5]
[ 2  3  4  5  6  7  9 10]
[ 2  3  4  5  6  6  7  7  9 10]
[ 2  3  4  5  6  6  7  7  9 10]
